# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee1a966ebed03901ece3dbe5ccfb4b194aebc06dfa5e7b56edd8f90913656181dbb7e292f48f7d04b3f5b29d464ea3e5b1f3d17fd582921d76113a139c904105

test:
  secret_key_base: 5396c93b4f003fcb1ccd05935cc23d508cc033853997324588f7bcacf2cc02ce5741c3e70fa677aa8d8c56a6184d310b0b5bea190398c7dd14631204f8c6cd08

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
